apiVersion: apps/v1
kind: Deployment
metadata:
  name: coachpro-deploy # Name of the deployment
spec:
  replicas: 2 # Number of pod replicas
  selector:
    matchLabels:
      app: coachpro # Selector to match pods
  template:
    metadata:
      labels:
        app: coachpro # Labels for pods
    spec:
      containers:
        - name: coachpro # Container name
          image: coachpro-app:{{BUILD_NUMBER}} # Docker image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050 # Port exposed
