apiVersion: apps/v1
kind: Deployment
metadata:
name: coachpro-deploy # Name of the deployment
spec:
replicas: 2 # specifies how many identical replicas (pods) of the application should be maintained, in this case, 2, which means Kubernetes will ensure that two pods running the specified container are always available
selector:
matchLabels:
app: coachpro # Selector to match pods managed by this deployment
template:
metadata:
labels:
app: coachpro # Labels applied to pods created by this deployment
spec:
containers:
- name: coachpro # Name of the container
image: coachpro-app # Docker image to use for the container
ports:
- containerPort: 5050 # Port that the container exposes