apiVersion: v1
kind: Service
metadata:
  name: coachpro-service
spec:
  type: NodePort
  selector:
    app: coachpro
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30080

