name: CoachPro CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: coachpro-app
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      #  Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install npm dependencies
        run: npm install

      # Install Playwright browsers 
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run backend tests
      - name: Run backend tests
        run: npm test

      # Run frontend tests
      - name: Run frontend tests
        run: npm run test-frontend

      # Setup Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$BUILD_NUMBER .

      # Start Minikube
      - name: Start Minikube
        uses: medyagh/setup-minikube@v0.0.14
        with:
          driver: docker

      # Load image into Minikube
      - name: Load Docker image into Minikube
        run: |
          minikube image load $IMAGE_NAME:$BUILD_NUMBER

      # Replace BUILD_NUMBER and deploy
      - name: Deploy to Kubernetes
        run: |
          sed "s/{{BUILD_NUMBER}}/$BUILD_NUMBER/g" deployment.yaml | kubectl apply -f -
          kubectl apply -f service.yaml

      # Verify deployment
      - name: Verify Kubernetes resources
        run: |
          kubectl get pods
          kubectl get services
